import { FinalProject, SourceFile, PackKind, CustomCommandDef, CommandParam, ScheduleDef } from "./types";

const ALIASES: Record<string,string> = { item:"items", block:"blocks", entity:"entities", recipe:"recipes", loot:"loot_tables", animation:"animations", controller:"animation_controllers", particle:"particles", feature:"features", feature_rule:"feature_rules", spawn_rule:"spawn_rules", trading:"trading", camera:"cameras", dialogue:"dialogue", structure:"structures", texture:"textures", sound:"sounds", ui:"ui", render_controller:"render_controllers", client_entity:"entity", language:"texts" };
const BEHAVIOR = new Set(["item","block","entity","recipe","loot","animation","controller","particle","feature","feature_rule","spawn_rule","trading"]);

export function parseSource(source:string): FinalProject {
  const m=source.match(/^\\s*project\\s+"([^"]+)"/m); if(!m) throw new Error("BedrockLang: missing project declaration.");
  const p:FinalProject={name:m[1],description:"Generated by BedrockLang 1.7.2",minEngineVersion:[1,21,0],behaviorFiles:[],resourceFiles:[],scripts:[],functions:[],commands:[],schedules:[]};
  const lines=source.replace(/\\r\\n/g,"\\n").split("\\n"); let i=0;
  while(i<lines.length){
    const line=lines[i].trim();
    if(!line||line.startsWith("//")||line.startsWith("project ")){i++;continue;}
    let m=line.match(/^description\\s+"([^"]+)"$/); if(m){p.description=m[1];i++;continue;}
    m=line.match(/^engine\\s+"(\\d+)\\.(\\d+)\\.(\\d+)"$/); if(m){p.minEngineVersion=[+m[1],+m[2],+m[3]];i++;continue;}
    m=line.match(/^command\\s+"([^"]+)"\\s*\\{$/); if(m){const r=readCommand(lines,i,m[1]);p.commands.push(r.value);i=r.next;continue;}
    m=line.match(/^every\\s+(\\d+)\\s+(ticks|seconds|minutes)\\s*\\{$/); if(m){const r=readBlock(lines,i);p.schedules.push({every:+m[1],unit:m[2] as ScheduleDef["unit"],body:r.body});i=r.next;continue;}
    m=line.match(/^event\\s+player\\.(join|leave|spawn)\\s*\\{$/); if(m){const r=readBlock(lines,i);p.scripts.push(eventScript(m[1],r.body));i=r.next;continue;}
    m=line.match(/^on\\s+([A-Za-z0-9_.:-]+)\\s*\\{$/); if(m){const r=readBlock(lines,i);p.scripts.push(genericEventScript(m[1],r.body));i=r.next;continue;}
    m=line.match(/^function\\s+"([^"]+)"\\s+"""?/); if(m&&line.includes('"""')){const r=readTriple(lines,i);p.functions.push("@@PATH:"+m[1].replace(/^\\/+/, "").replace(/\\.mcfunction$/,"")+".mcfunction\\n"+trimTriple(r.content));i=r.next;continue;}
    if(line.startsWith("script ")&&line.includes('"""')){const r=readTriple(lines,i);p.scripts.push(trimTriple(r.content));i=r.next;continue;}
    m=line.match(/^file\\s+(behavior|resource)\\s+"([^"]+)"\\s+"""/); if(m){const r=readTriple(lines,i);addFile(p,m[1] as PackKind,m[2],r.content);i=r.next;continue;}
    m=line.match(/^(item|block|entity|recipe|loot|animation|controller|particle|feature|feature_rule|spawn_rule|trading|camera|dialogue|structure|texture|sound|ui|render_controller|client_entity|language)\\s+"([^"]+)"\\s+"""/);
    if(m){const r=readTriple(lines,i);addFile(p,BEHAVIOR.has(m[1])?"behavior":"resource",normalizePath(m[2],m[1]),r.content);i=r.next;continue;}
    throw new Error("BedrockLang: unsupported syntax on line "+(i+1)+": "+line);
  } return p;
}

function readCommand(lines:string[],start:number,name:string):{value:CustomCommandDef,next:number}{
  const r=readBlock(lines,start); let description="BedrockLang command", permission:CustomCommandDef["permission"]="Any", cheatsRequired=false; const params:CommandParam[]=[]; const body:string[]=[];
  let executing=false;
  for(const raw of r.body){const x=raw.trim(); if(!x)continue;
    let m=x.match(/^description\\s+"([^"]+)"$/); if(m){description=m[1];continue;}
    m=x.match(/^permission\\s+(Any|GameDirectors|Admin|Host|Owner)$/i); if(m){permission=(m[1][0].toUpperCase()+m[1].slice(1)) as CustomCommandDef["permission"];continue;}
    m=x.match(/^cheats\\s+(true|false)$/); if(m){cheatsRequired=m[1]==="true";continue;}
    m=x.match(/^param\\s+(\\w+)\\s+([A-Za-z_][A-Za-z0-9_]*)\\s*(optional|required)?$/); if(m){params.push({type:mapParam(m[1]),name:m[2],optional:m[3]==="optional"});continue;}
    if(x==="execute {"||x==="execute"){executing=true;continue;} if(x==="}"){executing=false;continue;} if(executing)body.push(x);
  }
  return {value:{name,description,permission,cheatsRequired,params,body},next:r.next};
}
function mapParam(t:string){const m:Record<string,string>={boolean:"Boolean",bool:"Boolean",integer:"Integer",int:"Integer",float:"Float",string:"String",location:"Location",position:"Location",player:"PlayerSelector",players:"PlayerSelector",entity:"EntitySelector",entities:"EntitySelector",item:"ItemType",block:"BlockType",enum:"Enum",entitytype:"EntityType"};return m[t.toLowerCase()]||t;}
function readBlock(lines:string[],start:number){const body:string[]=[];let depth=0;for(let i=start;i<lines.length;i++){const x=lines[i].trim();if(x.endsWith("{"))depth++;if(x==="}"){depth--;if(depth===0)return{body,next:i+1};continue;}if(i!==start)body.push(x);}throw new Error("BedrockLang: unterminated block.");}
function readTriple(lines:string[],start:number){const first=lines[start],open=first.indexOf('"""');const out:string[]=[first.slice(open+3)];for(let i=start+1;i<lines.length;i++){const end=lines[i].indexOf('"""');if(end>=0){out.push(lines[i].slice(0,end));return{content:out.join("\n"),next:i+1};}out.push(lines[i]);}throw new Error("BedrockLang: unterminated triple-quoted block.");}
function trimTriple(s:string){return s.replace(/^\n/,"").replace(/\n$/,"");}
function eventScript(event:string,body:string[]){const statements=body.map(statement);if(event==="leave")return "world.afterEvents.playerLeave.subscribe((event)=>{\n"+indent(statements)+"\n});";return "world.afterEvents.playerSpawn.subscribe((event)=>{"+(event==="join"?"if(!event.initialSpawn)return;":"")+" const player=event.player;\n"+indent(statements)+"\n});";}
function genericEventScript(name:string,body:string[]){return "// BedrockLang event: "+name+"\n"+indent(body.map(statement));}
function statement(line:string){
  let m=line.match(/^player\\.message\\("((?:\\\\.|[^"])*)"\\)$/); if(m)return "player.sendMessage("+JSON.stringify(JSON.parse("\""+m[1]+"\""))+");";
  m=line.match(/^message\\s+"([^"]*)"$/); if(m)return "player.sendMessage("+JSON.stringify(m[1])+");";
  m=line.match(/^broadcast(?:\\s*\\()\\s*"([^"]*)"\\)?$/); if(m)return "world.sendMessage("+JSON.stringify(m[1])+");";
  m=line.match(/^command\\s+"([^"]*)"$/); if(m)return "system.run(()=>player.runCommand("+JSON.stringify(m[1])+"));";
  m=line.match(/^run\\s+"([^"]*)"$/); if(m)return "system.run(()=>player.runCommand("+JSON.stringify(m[1])+"));";
  m=line.match(/^log\\s+"([^"]*)"$/); if(m)return "console.log("+JSON.stringify(m[1])+");";
  return line.startsWith("//")?line:"throw new Error("+JSON.stringify("Unsupported BedrockLang statement: "+line)+");";
}
function indent(a:string[]){return a.map(x=>"    "+x).join("\n");}
function addFile(p:FinalProject,kind:PackKind,path:string,content:string){const f:SourceFile={pack:kind,path:normalizePath(path,"file"),content};(kind==="behavior"?p.behaviorFiles:p.resourceFiles).push(f);}
function normalizePath(path:string,alias:string){let p=path.replace(/\\/g,"/").replace(/^\/+/, "");if(!p.includes("/")&&ALIASES[alias])p=ALIASES[alias]+"/"+p;if(alias==="language"){if(!p.endsWith(".lang"))p=p.replace(/\.[A-Za-z0-9]+$/,"")+".lang";return p;}if(!/\.[A-Za-z0-9]+$/.test(p))p+=".json";return p;}
