import { FinalProject, SourceFile, PackKind } from "./types";

const RESOURCE_ALIASES: Record<string, string> = {
  item: "items",
  block: "blocks",
  entity: "entities",
  recipe: "recipes",
  loot: "loot_tables",
  animation: "animations",
  controller: "animation_controllers",
  particle: "particles",
  feature: "features",
  feature_rule: "feature_rules",
  spawn_rule: "spawn_rules",
  trading: "trading",
  camera: "cameras",
  dialogue: "dialogue",
  structure: "structures",
  texture: "textures",
  sound: "sounds",
  ui: "ui",
  render_controller: "render_controllers",
  client_entity: "entity",
  language: "texts"
};

export function parseSource(source: string): FinalProject {
  const projectMatch = source.match(/^\s*project\s+"([^"]+)"\s*$/m);
  if (!projectMatch) throw new Error("BedrockLang: missing project declaration.");
  const name = projectMatch[1];

  const project: FinalProject = {
    name,
    description: "Generated by BedrockLang",
    minEngineVersion: [1, 21, 0],
    behaviorFiles: [],
    resourceFiles: [],
    scripts: [],
    functions: []
  };

  const lines = source.replace(/\r\n/g, "\n").split("\n");
  let i = 0;

  while (i < lines.length) {
    const line = lines[i].trim();
    if (!line || line.startsWith("//")) { i++; continue; }
    if (line.startsWith("project ")) { i++; continue; }

    const triple = line.match(/^(resource|raw|item|block|entity|recipe|loot|animation|controller|particle|feature|feature_rule|spawn_rule|trading|camera|dialogue|structure|texture|sound|ui|render_controller|client_entity|language)\s+(?:(behavior|resource)\s+)?(?:"([^"]+)"\s+)?"""/);
    if (triple) {
      const kind = (triple[2] as PackKind | undefined) ?? (triple[1] === "item" || triple[1] === "block" || triple[1] === "entity" || triple[1] === "recipe" || triple[1] === "loot" || triple[1] === "animation" || triple[1] === "controller" || triple[1] === "particle" || triple[1] === "feature" || triple[1] === "feature_rule" || triple[1] === "spawn_rule" || triple[1] === "trading" ? "behavior" : "resource");
      const alias = triple[1];
      const explicitPath = triple[3];
      const folder = RESOURCE_ALIASES[alias] ?? "";
      const path = explicitPath ?? `${folder}/resource.json`;
      const result = readTriple(lines, i);
      const content = result.content;
      addFile(project, kind, normalizePath(path, alias), content);
      i = result.next;
      continue;
    }

    const rawFile = line.match(/^file\s+(behavior|resource)\s+"([^"]+)"\s+"""/);
    if (rawFile) {
      const result = readTriple(lines, i);
      addFile(project, rawFile[1] as PackKind, normalizePath(result.path, "file"), result.content);
      i = result.next;
      continue;
    }

    const event = line.match(/^event\s+player\.(join|leave|spawn)\s*\{$/);
    if (event) {
      const result = readEvent(lines, i);
      project.scripts.push(eventScript(event[1], result.body));
      i = result.next;
      continue;
    }

    const fn = line.match(/^function\s+"([^"]+)"\s+"""/);
    if (fn) {
      const result = readTriple(lines, i);
      project.functions.push(result.content.replace(/^\n/, "").replace(/\n$/, ""));
      const path = fn[1].replace(/^\/+/, "").replace(/\.mcfunction$/, "") + ".mcfunction";
      project.functions[project.functions.length - 1] = `@@PATH:${path}\n${project.functions[project.functions.length - 1]}`;
      i = result.next;
      continue;
    }

    const script = line.match(/^script\s+"""/);
    if (script) {
      const result = readTriple(lines, i);
      project.scripts.push(result.content.replace(/^\n/, "").replace(/\n$/, ""));
      i = result.next;
      continue;
    }

    throw new Error(`BedrockLang: unsupported syntax on line ${i + 1}: ${line}`);
  }

  return project;
}

function readTriple(lines: string[], start: number): { content: string; next: number; path: string } {
  const first = lines[start];
  const open = first.indexOf('"""');
  const tail = first.slice(open + 3);
  const out: string[] = [];
  if (tail.length) out.push(tail);
  let i = start + 1;
  while (i < lines.length) {
    const end = lines[i].indexOf('"""');
    if (end >= 0) {
      out.push(lines[i].slice(0, end));
      return { content: out.join("\n"), next: i + 1, path: "" };
    }
    out.push(lines[i]);
    i++;
  }
  throw new Error("BedrockLang: unterminated triple-quoted block.");
}

function readEvent(lines: string[], start: number): { body: string[]; next: number } {
  const body: string[] = [];
  let depth = 0;
  for (let i = start; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line.endsWith("{")) depth++;
    if (line === "}") {
      depth--;
      if (depth === 0) return { body, next: i + 1 };
      continue;
    }
    if (i !== start) body.push(line);
  }
  throw new Error("BedrockLang: unterminated event block.");
}

function eventScript(event: string, body: string[]): string {
  const statements: string[] = [];
  for (const line of body) {
    const msg = line.match(/^player\.message\("((?:\\.|[^"])*)"\)$/);
    if (msg) {
      const text = JSON.parse(`"${msg[1]}"`);
      if (event === "join" || event === "spawn") {
        statements.push(`player.sendMessage(${JSON.stringify(text)});`);
      } else {
        statements.push(`for (const p of world.getAllPlayers()) p.sendMessage(${JSON.stringify(text)});`);
      }
      continue;
    }
    const cmd = line.match(/^command\s+"((?:\\.|[^"])*)"$/);
    if (cmd) {
      const command = JSON.parse(`"${cmd[1]}"`);
      statements.push(`player.runCommand(${JSON.stringify(command)});`);
      continue;
    }
    if (line) throw new Error(`BedrockLang: unsupported event statement: ${line}`);
  }

  const callback = event === "join"
    ? `world.afterEvents.playerSpawn.subscribe((event) => { if (!event.initialSpawn) return; const player = event.player;\n${indent(statements)}\n});`
    : event === "spawn"
      ? `world.afterEvents.playerSpawn.subscribe((event) => { const player = event.player;\n${indent(statements)}\n});`
      : `world.afterEvents.playerLeave.subscribe((event) => {\n${indent(statements.map(s => s.replace(/player\\.runCommand/g, "world.getDimension(\\\"overworld\\\").runCommand")))}\n});`;
  return callback;
}

function indent(lines: string[]): string {
  return lines.map(x => "    " + x).join("\n");
}

function addFile(project: FinalProject, kind: PackKind, path: string, content: string): void {
  const file = { pack: kind, path, content };
  if (kind === "behavior") project.behaviorFiles.push(file);
  else project.resourceFiles.push(file);
}

function normalizePath(path: string, alias: string): string {
  let p = path.replace(/\\/g, "/").replace(/^\/+/, "");
  if (!p.includes("/")) {
    const folder = RESOURCE_ALIASES[alias];
    if (folder) p = `${folder}/${p}`;
  }
  if (!/\.[A-Za-z0-9]+$/.test(p)) p += ".json";
  if (alias === "language" && !p.endsWith(".lang")) p = p.replace(/\.json$/, ".lang");
  return p;
}
