import {
    mkdirSync,
    writeFileSync
} from "fs";

import {
    BedrockProjectIR,
    BedrockStatementIR
} from "../ir/ir";

export class BehaviorPackGenerator {

    generate(
        project: BedrockProjectIR
    ): string {

        const directory =
            `build/${project.name}/behavior_packs/${project.name}_BP`;

        mkdirSync(
            `${directory}/scripts`,
            {
                recursive: true
            }
        );

        const manifest =
            {
                format_version: 2,
                header: {
                    name:
                        `${project.name} Behavior Pack`,
                    description:
                        `Generated by BedrockLang`,
                    uuid:
                        "11111111-1111-4111-8111-111111111111",
                    version: [
                        1,
                        0,
                        0
                    ],
                    min_engine_version: [
                        1,
                        21,
                        0
                    ]
                },
                modules: [
                    {
                        type: "data",
                        uuid:
                            "22222222-2222-4222-8222-222222222222",
                        version: [
                            1,
                            0,
                            0
                        ]
                    },
                    {
                        type: "script",
                        language: "javascript",
                        uuid:
                            "33333333-3333-4333-8333-333333333333",
                        version: [
                            1,
                            0,
                            0
                        ],
                        entry:
                            "scripts/main.js"
                    }
                ],
                dependencies: [
                    {
                        module_name:
                            "@minecraft/server",
                        version:
                            "2.10.0"
                    }
                ]
            };

        writeFileSync(
            `${directory}/manifest.json`,
            JSON.stringify(
                manifest,
                null,
                2
            ),
            "utf8"
        );

        const script =
            this.generateScript(
                project
            );

        writeFileSync(
            `${directory}/scripts/main.js`,
            script,
            "utf8"
        );

        return directory;
    }

    private generateScript(
        project: BedrockProjectIR
    ): string {

        const lines: string[] = [];

        lines.push(
            `import { world } from "@minecraft/server";`
        );

        lines.push("");

        for (
            const event
            of project.behaviorPack.events
        ) {

            if (
                event.target !== "player"
            ) {
                continue;
            }

            if (
                event.event === "join"
            ) {

                lines.push(
                    `world.afterEvents.playerJoin.subscribe((event) => {`
                );

                this.generateEventStatements(
                    lines,
                    event.statements
                );

                this.generateFunctionCall(
                    lines,
                    event.event
                );

                lines.push(
                    `});`
                );

                lines.push("");
            }

            if (
                event.event === "leave"
            ) {

                lines.push(
                    `world.afterEvents.playerLeave.subscribe((event) => {`
                );

                this.generateFunctionCall(
                    lines,
                    event.event
                );

                lines.push(
                    `});`
                );

                lines.push("");
            }
        }

        return lines.join("\n");
    }

    private generateEventStatements(
        lines: string[],
        statements: BedrockStatementIR[]
    ): void {

        for (
            const statement
            of statements
        ) {

            lines.push(
                ...this.generateStatement(
                    statement
                )
            );
        }
    }

    private generateStatement(
        statement: BedrockStatementIR
    ): string[] {

        switch (
            statement.type
        ) {

            case "PlayerMessage":

                return [
                    `    world.sendMessage(${JSON.stringify(statement.message)});`
                ];

            default:

                throw new Error(
                    `Unsupported behavior-pack statement '${statement.type}'.`
                );
        }
    }

    private generateFunctionCall(
        lines: string[],
        eventName: string
    ): void {

        lines.push(
            `    world.getDimension("overworld").runCommand("function events/player_${eventName}");`
        );
    }
}