import { mkdirSync, writeFileSync } from "fs";
import { v4 as uuidv4 } from "uuid";
import { ProgramNode, ProjectNode } from "../parser/ast";
import { ScriptGenerator } from "./scriptGenerator";

export class ProjectGenerator {

    generate(ast: ProgramNode): void {
        const project = this.findProject(ast);

        const projectName = project.name;

        const outputDirectory =
            `build/${projectName}`;

        const behaviorPackDirectory =
            `${outputDirectory}/behavior_packs/${projectName}_BP`;

        const resourcePackDirectory =
            `${outputDirectory}/resource_packs/${projectName}_RP`;

        mkdirSync(behaviorPackDirectory, {
            recursive: true
        });

        mkdirSync(resourcePackDirectory, {
            recursive: true
        });

        this.generateBehaviorPackManifest(
            behaviorPackDirectory,
            projectName
        );

        this.generateResourcePackManifest(
            resourcePackDirectory,
            projectName
        );

        const scriptGenerator = new ScriptGenerator();

        scriptGenerator.generate(
            ast,
            behaviorPackDirectory
        );

        console.log(
            `Generated Bedrock project: ${projectName}`
        );

        console.log(
            `Output: ${outputDirectory}`
        );
    }

    private findProject(
        ast: ProgramNode
    ): ProjectNode {

        const project = ast.declarations.find(
            declaration =>
                declaration.type === "Project"
        );

        if (
            !project ||
            project.type !== "Project"
        ) {
            throw new Error(
                "BedrockLang project is missing a project declaration."
            );
        }

        return project;
    }

    private generateBehaviorPackManifest(
        directory: string,
        projectName: string
    ): void {

        const headerUuid = uuidv4();
        const moduleUuid = uuidv4();

        const manifest = {
            format_version: 2,

            header: {
                name: `${projectName} Behavior Pack`,
                description: "Generated by BedrockLang",
                uuid: headerUuid,
                version: [1, 0, 0],
                min_engine_version: [1, 21, 0]
            },

            modules: [
                {
                    type: "script",
                    language: "javascript",
                    uuid: moduleUuid,
                    version: [1, 0, 0],
                    entry: "scripts/main.js"
                }
            ],

            dependencies: [
                {
                    module_name: "@minecraft/server",
                    version: "1.17.0"
                }
            ]
        };

        writeFileSync(
            `${directory}/manifest.json`,
            JSON.stringify(manifest, null, 2)
        );
    }

    private generateResourcePackManifest(
        directory: string,
        projectName: string
    ): void {

        const headerUuid = uuidv4();
        const moduleUuid = uuidv4();

        const manifest = {
            format_version: 2,

            header: {
                name: `${projectName} Resource Pack`,
                description: "Generated by BedrockLang",
                uuid: headerUuid,
                version: [1, 0, 0],
                min_engine_version: [1, 21, 0]
            },

            modules: [
                {
                    type: "resources",
                    uuid: moduleUuid,
                    version: [1, 0, 0]
                }
            ]
        };

        writeFileSync(
            `${directory}/manifest.json`,
            JSON.stringify(manifest, null, 2)
        );
    }
}