import {
    mkdirSync,
    writeFileSync
} from "fs";

import {
    v4 as uuidv4
} from "uuid";

import {
    BedrockProjectIR
} from "../ir/ir";

export class ResourcePackGenerator {

    generate(
        project: BedrockProjectIR
    ): string {

        const directory =
            `build/${project.name}/resource_packs/${project.name}_RP`;

        mkdirSync(
            directory,
            {
                recursive: true
            }
        );

        this.generateManifest(
            directory,
            project
        );

        return directory;
    }

    private generateManifest(
        directory: string,
        project: BedrockProjectIR
    ): void {

        const headerUuid =
            uuidv4();

        const moduleUuid =
            uuidv4();

        const manifest = {

            format_version: 2,

            header: {

                name:
                    project.resourcePack.name,

                description:
                    "Generated by BedrockLang",

                uuid:
                    headerUuid,

                version:
                    [1, 0, 0],

                min_engine_version:
                    [1, 21, 0]
            },

            modules: [

                {

                    type:
                        "resources",

                    uuid:
                        moduleUuid,

                    version:
                        [1, 0, 0]
                }
            ]
        };

        writeFileSync(
            `${directory}/manifest.json`,
            JSON.stringify(
                manifest,
                null,
                2
            ),
            "utf8"
        );
    }
}